version: "3.8"

services:
  frontend:
    # image: deploy-docker/frontend
    container_name: frontend
    build: ./front-end
    env_file: ./back-end/.env.docker
    ports:
      - "80:8080"
  backend:
    # image: deploy-docker/backend
    container_name: backend
    build: ./back-end
    env_file: ./back-end/.env.docker
    ports:
      - "3334:3334"
    depends_on:
      - database
  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

networks:
  docker-deploy:
volumes:
  shared:
